### ISSUE TITLE
Adding a Community Standards

### ISSUE THREAD

**Issue by agung2001** [leocaseiro/Wordpress-Plugin-Custom-Options-Plus#27]
Hi Leo, 👋😄  
my name is agung,  

I think this repository still doesn't have GitHub [Community Standards](https://github.com/leocaseiro/WordPress-Plugin-Custom-Options-Plus/community).  
If that's ok for you I would like to contribute to this repo by creating a pull request containing those files.  
You can review the changes and decide to merge them later.

Just let me know what you think
Cheers mate 😄🍻

**Comment by leocaseiro** [comment]
Hi, I've never heard of that. If. You are interested in contributing, what exactly are you planning to implement or fix?

Just raise an issue for what you think we need, and we can discuss for that.

Just because there isn't a community standard, doesn't mean I wouldn't accept contributions.

As much as it's a nice new feature or a proper fix, it should be fine.

**Comment by agung2001** [comment]
Hi Leo @leocaseiro , 👋😄

yup, I have an idea to add an issue template.
I just found some interesting GitHub Issue templates for reporting a [bug](https://github.com/stevemao/github-issue-templates/blob/master/.github/ISSUE_TEMPLATE/BUG-REPORT.yml) and [requesting a new feature](https://github.com/stevemao/github-issue-templates/blob/master/.github/ISSUE_TEMPLATE/FEATURE-REQUEST.yml).

currently, this repo/plugin doesn't have the issue template. by adding issue templates :
- this repo can automatically generate structured issue templates
- and tag them by their type (bug report or feature request)

I also had another idea : 
- adding [WPCS (WordPress Code Sniffer)](https://github.com/WordPress/WordPress-Coding-Standards) for sniffing 
- adding [prettier](https://prettier.io/) for auto code formatting

but one at a time, after we add the issue template we can discuss more of these 😄
so what do u think. if that's ok for you I'm gonna create a PR (Pull Request) containing issue templates.

thx Leo, anyway in advance happy new years bro 😄🎉

**Comment by leocaseiro** [comment]
Hi @agung2001, I appreciate your plans to improve the dev loop of this plugin, but what I didn't understand is what is the feature you are going to add to the plug-in? Or what bug you are trying to fix?

Can you please raise that before trying to add a bunch of dev loop files to maintain?

I am very welcome for contributions, but I wrote this plug-in 10 years ago, and I barely had any external contributions, so I think adding some extra files, and prettier wouldn't aggregate much for the extension that has been working for over 10 years.
